### ISSUE TITLE
Authelia - Expand configuration scope

### ISSUE THREAD

**Issue by saltydk** [saltyorg/Saltbox#100]
Build out the role so that we can take a list of users/passwords or look at alternative ways to manage them externally so that Saltbox can fully manage Authelia's configuration which would allow for us to automatically upgrade the algorithm whenever it is needed.

This issue will also be taking any ideas you guys might have for the role rewrite so please submit them here as soon as possible.

May incorporate https://github.com/saltyorg/Saltbox/issues/50 as part of this rework.

- [ ] Cover situation where user changes the domain. Migrate config, warn user or?

**Comment by owine** [comment]
To account for potential future breaking config changes in Authelia, refactor the authelia-reset operations to upgrade the config based on deprecations rather then reset the config entirely.

**Comment by saltydk** [comment]
Look at migrating the role from using authelia_redis to authelia-redis as it triggers a warning due to hostnames technically not being allowed to have underscores in them.

**Comment by saltydk** [comment]
@owine wouldn't we consider this completed already or?
