### ISSUE TITLE
[Feature request] add ansible_distribution_release fallback for supported supported os 

### ISSUE THREAD

**Issue by hereisderek** [saltyorg/Saltbox#101]
---

**Describe the problem**
Sometimes when a new os version was released but third party apps (such as docker and mergerfs) are still falling behind on the official repo for that release, it's most likely safe to fallback to the repos for one distribution prior, in this case if i have updated to 22.10 (kinetic), I can still use jammy before official support was added. 
Using a fallback of ansible_distribution_release will allow us to bridge the gap for the time being, and automatically update to the latest on the next update after the official supported was added 

**Describe any solutions you think might work**
keep a global variable `distribution_release_fallback: "jammy"` for the latest known os release (specific to the OS, in this case Ubuntu), and when installing dependencies that are known to have releases for specific os versions that are usually lag behind (docker and mergerfs are the ones i had trouble), we first check if the url is valid (`docker_apt_checker_distribution_url`), if not continue with the fallback instead

```
docker_apt_checker_base_url: "https://download.docker.com/linux"

docker_apt_checker_distribution_url: "{{docker_apt_checker_base_url}}/{{ ansible_distribution | lower }}/dists/{{ ansible_distribution_release | lower }}"
```

**Comment by owine** [comment]
I don't see much of an appetite to make it easy to run an OS unsupported by Saltbox.

**Comment by saltydk** [comment]
Neither docker nor mergerfs are installed through apt though.
