### ISSUE TITLE
[feature] support {{ role_name }}_paths_folders_list_custom to work with prowlarr_docker_volumes_custom

### ISSUE THREAD

**Issue by hereisderek** [saltyorg/Saltbox#103]
---

**Describe the problem**
i have a really small ssd therefore i need to be mindful where to use the precious space at, i was doing some `du` on the `/opt` folder, and found a few folders (e.g. metadata/cache in plex) i'm hoping to move out of /opt (,which i plan to host on the ssd). I noticed that we can override `radarr_docker_volumes_custom` in the `localhost.yml` folder, which is really nice, however I couldn't find a way to create the host folder if they don't exist. 

**Describe any solutions you think might work**
i guess we could create a custom role just for this, but maybe we could follow the pattern of `radarr_docker_volumes_custom` and create something like `{{ role_name }}_paths_folders_list_custom `, and create those folders (maybe even check permissions) in the `common` role after reading those values out?

**Additional context**

**Comment by saltydk** [comment]
You can override the current folder list. I agree that it makes more sense to have a separate variable in this case and will think on how we can rework the roles to make such edits less annoying to do that having to edit all the roles.

**Comment by saltydk** [comment]
Something like this? https://github.com/saltyorg/Saltbox/commit/583ea5c89af45fc2ac5c07732f82f3dc81500bee

**Comment by hereisderek** [comment]
> Something like this? [583ea5c](https://github.com/saltyorg/Saltbox/commit/583ea5c89af45fc2ac5c07732f82f3dc81500bee)

pretty much, except that i still don't see a way to add custom folder lists

**Comment by saltydk** [comment]
You just add ```yaml
rolename_paths_folders_list_custom:
  - /some/folder``` to the inventory.

**Comment by saltydk** [comment]
Inventory is covered here https://docs.saltbox.dev/saltbox/inventory/

**Comment by hereisderek** [comment]
> 

ah, somehow I missed that, my bad.

yes this is exactly what i wanted

**Comment by saltydk** [comment]
I'll close this then.
