### ISSUE TITLE
[featuer] allow optionally specify user id and group id when creating account

### ISSUE THREAD

**Issue by hereisderek** [saltyorg/Saltbox#104]
---

**Describe the problem**
allow optionally specify user id and group id when creating the account
I'm using proxmox's lxc and there's bit of user id mapping best if we could get a predetermined id 

**Describe any solutions you think might work**
both of `ansible.builtin.group` and `ansible.builtin.user:` have build in options to supply an id, I'm happy with just error out if given account exist and with different id 

**Additional context**

**Comment by saltydk** [comment]
https://github.com/saltyorg/Saltbox/commit/68ba78c302dcfb8cd49f32fcb2c6d400ffa30e23
