### ISSUE TITLE
Container to keep CF DNS in sync with Traefik Docker labels

### ISSUE THREAD

**Issue by owine** [saltyorg/Saltbox#120]
---

**Describe the problem**
Instead of handling DNS at the role level, provision a container that monitors the Docker socket (via read only proxy) for Traefik labels that contain a domain/subdomain Host entry and ensure those are in sync with the server's public IP. This would handle creation, removal and updating records as containers are added/removed/changed. 

**Describe any solutions you think might work**
A clear and concise description of any solutions or features you've considered.

**Additional context**

**Comment by powerdude** [comment]
I use a combination of `oznu/cloudflare-ddns` and `tiredofit/traefik-cloudflare-companion` with `ansible-nas`

**Comment by saltydk** [comment]
We'll be making our own version so it ties in better with Saltbox.

**Comment by Barrow1990** [comment]
This would be a very useful addition. How is this coming along? And would this be apart of the main suite of apps or an additional 1 to install manually

**Comment by saltydk** [comment]
It is already in our test branch.

**Comment by saltydk** [comment]
You can deploy it manually if you want to help test it. Can probably find the relevant information in order to manually add it with docker compose here: https://github.com/saltyorg/Saltbox/blob/traefik3/roles/ddns/defaults/main.yml
