### ISSUE TITLE
Gluetun Role

### ISSUE THREAD

**Issue by SRBGod** [saltyorg/Saltbox#136]
---

**Describe the problem**
Gluetun is a flexible VPN solution that allows any container to be routed through it using the container network feature in docker. Would be immensely useful for tunneling apps as needed through various VPN providers.

**Describe any solutions you think might work**
A simple role would allow for users to run the gluetun container and no longer need to fuss about with containers that have VPN features, instead setting up gluetun once and being able to use it for as many containers as needed.

**Additional context**
I tried and failed to create this role but am hoping it can become part of the main project at some point. It is very handy. (https://github.com/qdm12/gluetun)

**Comment by saltydk** [comment]
The way we setup instances won't function as is with a VPN container so not sure I want this in the main project. We can do a Sandbox role instead and explain the limitations with instances. There is no functionality needed in Saltbox to make it work with a Sandbox role anyway as the necessary variables are already in place.

**Comment by SRBGod** [comment]
Closing and moving to sandbox
