### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by jodiekurnia** [saltyorg/Saltbox#143]
Oracle Cloud offer generous always free including 4vcpu and 24gb ram, but it's using n1 arm cpu,
is there any technical reason why you didn't support aarch64/arm64?

**Comment by saltydk** [comment]
Not personally interested in having an arm based system so it wouldn't be validated in any meaningful sense of the word thus we just decided not to support it. It is the same reason we do not do support any other distribution of Linux as well, it takes time to validate stuff.
