### ISSUE TITLE
Plex: Add delay before stopping container for extra tasks

### ISSUE THREAD

**Issue by owine** [saltyorg/Saltbox#149]
Seen a few instances where the container stop/start for `plex_extra_tasks` seems to happen too quickly after container creation/start and the stop attempt hangs and does not complete causing the playbook to exit.

Some ideas:
- Create container in stopped state if there is a need to run the extra tasks
- Add a delay to ensure the container has adequate time to start and complete tasks (DB migrations, etc)
- Change order to setup plugins between container removal and creation

**Comment by saltydk** [comment]
I assume this is covered by https://github.com/saltyorg/Saltbox/commit/a857999c5530974dc3c85c8f5be054287dd74f7d if not then let me know.
