### ISSUE TITLE
plex_db: Integrity-check-only Setting

### ISSUE THREAD

**Issue by keldian** [saltyorg/Saltbox#151]
Add an option for the playbook to skip database optimization tasks regardless of the integrity check result, add a `notify` task to send a message if the check was failed.

The idea is to leverage the role to schedule regular integrity checks and be notified when there's database corruption.

**Comment by saltydk** [comment]
Implemented in traefik3 commit https://github.com/saltyorg/saltbox/commit/3ca11263eec737e524878ada294a0479498fa305
