### ISSUE TITLE
add xtream codes clone

### ISSUE THREAD

**Issue by daveftw84** [saltyorg/Saltbox#158]
would be neat if we can setup our own eyeptY server or just use vod to make a server. 
i would like something that just serves media and thats it. no resume points, transcoding, tracking, etc

**Comment by chazlarson** [comment]
This seems like an app request for sandbox.  Please make a request there with some specifics, and I can't find any information on something called "eyeptY"

**Comment by keldian** [comment]
I think he means IPTV but that is one hell of a misspelling.

**Comment by daveftw84** [comment]
i was being coy about it
