### ISSUE TITLE
Fatal error: Hotio NZBGet down??

### ISSUE THREAD

**Issue by bezzpezz** [saltyorg/Saltbox#161]
**Describe the bug**
Hey,

FYI,

I was just trying to run the sb install saltbox and I am now getting this fatal error:
fatal: [localhost]: FAILED! => {"attempts": 1, "changed": false, "msg": "Error pulling image cr.hotio.dev/hotio/nzbget:release - 500 Server Error for http+docker://localhost/v1.43/images/create?tag=release&fromImage=cr.hotio.dev%2Fhotio%2Fnzbget: Internal Server Error (\"Head \"https://ghcr.io/v2/hotio/nzbget/manifests/release\": denied\")"}

Tried accessing "https://ghcr.io/v2/hotio/nzbget/manifests/release" in browser but it seems to be down or unauthorised??

Are there any workarounds??

- Cheers

**To Reproduce**
1. Run sb install saltbox 

**Expected behavior**
Hotio NZBGet docker pulls as usual

**Screenshots**
N/A - see above error

**Logs**
you probably don't need logs. 

If issue occurs during Ansible playbook, run playbook with `-vv` to output detailed debug log.
-vv had the same output

**System Information**

Linux saltbox 5.15.0-79-generic #86~20.04.2-Ubuntu SMP Mon Jul 17 23:27:17 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

 - Operating System: [e.g. Ubuntu Server 20.04 LTS]
 - Linux Kernel: [e.g. 5.8]

**Additional context**
None

**Comment by owine** [comment]
This has already been fixed. Run `sb update` before deploying.
