### ISSUE TITLE
2FA Authelia

### ISSUE THREAD

**Issue by notlimahrelyt** [saltyorg/Saltbox#169]
How do I enable 2FA in Authelia? Can someone provide a sample config? I'm following Authelia's documentation but I still can't figure it out.

**Comment by saltydk** [comment]
You change it under access_control, one_factor to two_factor. 

Alternatively set 
```yaml
authelia_access_control_policy: "two_factor"
```
Using the inventory and reset authelia with sb install authelia-reset. Just be aware that currently running that reset will cause you to have to setup 2FA all over so don't do it once setup.

We generally only provide support on our discord so I am closing this.
