### ISSUE TITLE
Add ThreadFin

### ISSUE THREAD

**Issue by 0xW1sKy** [saltyorg/Saltbox#174]
---

**Describe the problem**
A clear and concise description of the problem you're looking to solve.

Please add a set of configurations for ThreadFin (current accepted version of xteve)
Used for viewing liveTV/IPTV on Plex/JellyFin

**Describe any solutions you think might work**
A clear and concise description of any solutions or features you've considered.

**Additional context**

**Comment by owine** [comment]
Exists in sandbox
