### ISSUE TITLE
Ansible Cloudflare Fetch Record Error

### ISSUE THREAD

**Issue by mmikhail100** [saltyorg/Saltbox#177]
When running and sb install command, the ansible playbook fails on Cloudflare DNS record fetch. Have been running sb for over a year now, though mostly hands off, without issues. Thanks for your help!

TASK [dns : Cloudflare | Add DNS Record | Fetch Record information] ******************************************************************************************
Wednesday 01 November 2023  19:39:15 +0100 (0:00:00.040)       0:00:13.286 **** 
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/srv/cloudflare/venv/bin/python3 /srv/cloudflare/cloudflare.py --auth_key 'REDACTED' --auth_email 'REDACTED' --zone_name 'REDACTED' --record 'REDACTED'", "delta": "0:00:00.002274", "end": "2023-11-01 19:39:15.992439", "msg": "non-zero return code", "rc": 127, "start": "2023-11-01 19:39:15.990165", "stderr": "/bin/sh: 1: /srv/cloudflare/venv/bin/python3: not found", "stderr_lines": ["/bin/sh: 1: /srv/cloudflare/venv/bin/python3: not found"], "stdout": "", "stdout_lines": []}
...ignoring

TASK [dns : Cloudflare | Add DNS Record | Print Failure Output] **********************************************************************************************
Wednesday 01 November 2023  19:39:16 +0100 (0:00:00.169)       0:00:13.455 **** 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "/bin/sh: 1: /srv/cloudflare/venv/bin/python3: not found"}

 - Operating System: Ubuntu 22.04.3 LTS
 - Linux Kernel: 6.2.0-36-generic

**Comment by owine** [comment]
Add `-e cloudflare_reinstall=true` to one sb install run and it should get sorted

**Comment by mmikhail100** [comment]
Solved, didn't realize there was a tag to force cloudflare reinstall. Thanks!
