### ISSUE TITLE
Add xteve/Threadfin?

### ISSUE THREAD

**Issue by bryanhoffman04** [saltyorg/Saltbox#179]
This allows you to get IPTV channels with m3u lists in plex/jellyfin.
Old project was xteve, looks like some forked it to threadfin.

https://github.com/Threadfin/Threadfin
https://github.com/xteve-project/xTeVe

I personally have used xTeVe for years without issues, haven't tested threadfin yet.

**Comment by thatsnasty** [comment]
https://docs.saltbox.dev/sandbox/apps/xteve/

https://docs.saltbox.dev/sandbox/apps/threadfin/
