### ISSUE TITLE
Adapt Traefik templating to support multiple subdomains

### ISSUE THREAD

**Issue by owine** [saltyorg/Saltbox#183]
Initial thought was to detect root domain or `www` subdomain and automatically add the other but expanding that to support a list of subdomains would be a nice potential feature.

```
wordpress_web_subdomains:
  - "{{ wordpress_name }}"
  - "thething"
  - "www"
  ```
  or
  ```
  wordpress_web_fqdn:
  - "{{ wordpress_web_subdomain }}.{{ wordpress_web_domain }}"
  - "www.{{ wordpress_web_domain }}"
  - "domain2.tld"
  ```

**Comment by saltydk** [comment]
I forget what this was for, just Traefik? If so it is probably solved with traefik_host_override since you can override the Host string to whatever you want. Or was this wanting CF integration?
