### ISSUE TITLE
Integrate nvidia and docker tasks in the docker role

### ISSUE THREAD

**Issue by saltydk** [saltyorg/Saltbox#186]
As part of this change explore moving the nvidia install to an earlier point, maybe as part of preinstall.

The current format is very entangled and error prone if the user doesn't understand that updating docker requires running the nvidia role again after.

**Comment by saltydk** [comment]
Nvidia integration will be removed so this no longer makes sense.

**Comment by kabroxiko** [comment]
How do we use nvidia GPU now?

**Comment by saltydk** [comment]
We don't really do support in Github issues. The announcement on discord described the changes we did to allow users to manage the Nvidia bits on their own, if you need help with that you would have to ask on the discord.
