### ISSUE TITLE
Cadvisor doesn't deploy with any traefik reverse proxy labels

### ISSUE THREAD

**Issue by edrock200** [saltyorg/Saltbox#187]
**Describe the bug**
Cadvisor has a web interface, on 8080, but saltbox doesn't deploy with the traefik labels needed to make it accessible via the reverse proxy.

**To Reproduce**
1. sb install cadvisor
2. docker inspect cadvisor # look for traefik labels

**Expected behavior**
Traefik labels get deployed with cadvisor

**System Information**

 - Operating System: Ubuntu Server 22.04 
 - Linux Kernel: 6.2.7

**Comment by saltydk** [comment]
Do you have a use case that requires external access? It was built this way since the access externally was not required.

**Comment by owine** [comment]
Just for the record, given the way the templating works, you can set the traefik variables via inventory to make the webui accessible via traefik. The DNS would require manual setup

**Comment by saltydk** [comment]
I don't mind exposing the dashboard behind Authelia but if you need the API endpoints you'd have to do that research and make a PR.
