### ISSUE TITLE
Different Folder name for rclone

### ISSUE THREAD

**Issue by N-sherwood** [saltyorg/Saltbox#192]
Hello 

I got idea can we have different folder then rclone name
Eg 

Rclone name is Dropbox-media

Folder in remote like Dropbox or something 

Please

**Comment by saltydk** [comment]
This is already possible, ask on the discord if you need help with it.

**Comment by saltydk** [comment]
It is also written on the docs page for the initial install under the
configuration step
https://docs.saltbox.dev/saltbox/install/install/#step-2-configuration
