### ISSUE TITLE
Switch to Let's Encrypt because ZeroSSL is not available in some countries resulting in ""Access Denied: Selling and offering services through our platform are restricted in your region." error.

### ISSUE THREAD

**Issue by zeretrelle** [saltyorg/Saltbox#213]
**Describe the problem**

While installing Saltbox I encountered this error:

"Access Denied: Selling and offering services through our platform are restricted in your region.

**Describe any solutions you think might work**

Use Let's Encrypt instead of  ZeroSSL or provide the way to use Let's Encrypt certificates via a specific installation command flag.

It's always better to rely on a company that doesn't mix politics and IT.

**Comment by saltydk** [comment]
The default is Let's Encrypt so what are you asking for here?

**Comment by zeretrelle** [comment]
Then why am I getting this error when running the installation command?


TASK [traefik : ZeroSSL | Get new credentials] *********************************************************************************************************************************************************************************
Monday 27 May 2024  02:01:16 +0300 (0:00:00.027)       0:06:49.449 ************
fatal: [localhost]: FAILED! => {"changed": false, "connection": "close", "content": "Access Denied: Selling and offering services through our platform are restricted in your region. Thank you for your understanding.", "content_length": "130", "content_type": "text/plain", "date": "Sun, 26 May 2024 23:01:17 GMT", "elapsed": 0, "msg": "Status code was 403 and not [200]: HTTP Error 403: Forbidden", "redirected": false, "server": "awselb/2.0", "status": 403, "url": "https://api.zerossl.com/acme/eab-credentials-email"}

**Comment by saltydk** [comment]
https://github.com/saltyorg/Saltbox/commit/b720f8601d43f1d4a7515119f1513d7a6b4ebf2f
