### ISSUE TITLE
URL Error 500 for new deployed apps

### ISSUE THREAD

**Issue by gntech-dev** [saltyorg/Saltbox#267]
Hello guys, I'm facing some weird issue, after installing any app, new one non installed before I'm getting error 500 when try to open on the browser, previous used apps work normally. 

But for example, when i run:

sb install portainer, command runs normally and shows successful install, records created at Cloudflare, and pointed to correct ip, but app don't open and just show error 500.

Tried to get any traefik logs with docker logs traefik, but it doesn't show anything. 

**System Info**
OS: Ubuntu 24.04.1 LTS x86_64 
Kernel: 6.8.0-44-generic 
CPU: 13th Gen Intel i5-13500 (20) @ 4.800G 

**Logs**
Traefik logs empty 
![image](https://github.com/user-attachments/assets/66f54812-10b3-45e0-8f62-0522cb2ebf0d)

![image](https://github.com/user-attachments/assets/862c5a24-095d-4f6a-9b18-96ef12e74500)
![image](https://github.com/user-attachments/assets/b1e64395-eead-4e31-9d9f-0b9c20d7558c)

Thanks in advance.

**Comment by owine** [comment]
My guess is you need to redeploy Traefik via `sb install traefik` due to a middleware change from several months back. Try that and join the Discord if you need further support.

**Comment by gntech-dev** [comment]
> My guess is you need to redeploy Traefik via `sb install traefik` due to a middleware change from several months back. Try that and join the Discord if you need further support.

Thanks, I run sb install traefik to reinstall traefik but doesn't help, gonna try on discord.
