### ISSUE TITLE
Authentik Setup not working

### ISSUE THREAD

**Issue by aronjanosch** [saltyorg/Saltbox#269]
**Describe the bug**
I want to switch to authentik. During the installation the playbook get stuck at:
```
TASK [authentik : Validate bootstrap token (retry until Authentik is ready)] **********************************************************************************************************
Tuesday 08 October 2024  01:43:52 +0200 (0:00:00.114)       0:02:23.079 *******
FAILED - RETRYING: [localhost]: Validate bootstrap token (retry until Authentik is ready) (999 retries left).
FAILED - RETRYING: [localhost]: Validate bootstrap token (retry until Authentik is ready) (998 retries left).
...
FAILED - RETRYING: [localhost]: Validate bootstrap token (retry until Authentik is ready) (934 retries left).
FAILED - RETRYING: [localhost]: Validate bootstrap token (retry until Authentik is ready) (933 retries left)
```
I did the installation before changing the inventory file as well as after it. All containers are healthy and I even waited 25 minutes.

**To Reproduce**
1. if present remove the ```/opt/authentik``` folder
2. ```sb install authentik```
3. wait

**Expected behavior**
The installation completes successfully the containers start and i can reach the auth.yourdomain.com url, but because the setup gets stuck, no admin user is created.

I think using authentik_host the container is not reachable and instead the domain should be used.

This works (i got the AUTHENTIK_BOOTSTRAP_TOKEN from the ansible verbose logs):
```curl -H "Authorization: Bearer <AUTHENTIK_BOOTSTRAP_TOKEN>" https://auth.yourdomain.com/api/v3/core/users/me/```

**Screenshots**

**Logs**

**System Information**

 - Operating System: Ubuntu 20.04 LTS

**Comment by saltydk** [comment]
We handle support on the discord, not on Github.
