### ISSUE TITLE
Authentik Postgres 12 Database EOL

### ISSUE THREAD

**Issue by Barrow1990** [saltyorg/Saltbox#272]
**Describe the bug**
The database that comes with authentik is [EOL](https://www.postgresql.org/about/news/postgresql-163-157-1412-1315-and-1219-released-2858/#:~:text=PostgreSQL%2012%20EOL%20Notice,versioning%20policy%20for%20more%20information.) in November 2024.

**To Reproduce**
Install Authentik

**Expected behavior**
To be on a supported version / the latest version on install.

**Additional context**
Install the newest version on a clean install / install a different database engine that isnt as fragile.

Would seem theres documentation for an upgrade [docs](https://docs.goauthentik.io/docs/troubleshooting/postgres/upgrade_docker)
Maybe have another role to upgrade the db etc

**Comment by owine** [comment]
Postgres upgrade handling is on a test branch and should be merged soon to allow for Postgres versions to be bumped and upgraded handled gracefully.

**Comment by saltydk** [comment]
Yeah, it is in the crowdsec branch which will hopefully be merged within the next week or so. Just doing some final validation to attempt to hopefully limit the, oh no we locked out the user from their box, events that will happen without fail with this kind of addition 🥲
