### ISSUE TITLE
Themepark themes not working

### ISSUE THREAD

**Issue by brainwalker** [saltyorg/Saltbox#44]
The theme park themes doesn't load the script for Hotio. Changing this code fixed it for me.

https://github.com/saltyorg/Saltbox/blob/5974b775600ae9c305ccf042edad7074b3b867e5/roles/radarr/defaults/main.yml#L121

`  - "{{ radarr_paths_location }}/98-themepark.sh:/etc/cont-init.d/99-themepark"`

Same issue with all the other roles that can use themepark (Sonarr / Readarr / nzbget / etc...)

Ref: https://docs.theme-park.dev/setup/#hotio-containers

**Comment by saltydk** [comment]
That rename does nothing as far as I can tell. Radarr install loads the theme-park just fine in the fresh install I just did.

**Comment by saltydk** [comment]
Did you actually enable it?

**Comment by brainwalker** [comment]
You are correct. Just enabling the theme without renaming fixed it. Sorry for the confusion.

`radarr_themepark_enabled: true`

**Comment by saltydk** [comment]
No worries :)
