### ISSUE TITLE
Migration via a cloudbox backup.

### ISSUE THREAD

**Issue by maximuskowalski** [saltyorg/Saltbox#48]
Explore the possibility of a specific role or flag to indicate a Cloudbox backup is being used and avoid bringing in stale settings.

Ideas could be as simple as setting a shortcut on the restore drive, or dragging the wanted tarred app files into the saltbox default.

I imagine this being required only for those that are quite new to X box or do not understand the backup restore process.

I would consider priority low as it would be a one shot use.

Similarly might be to consider the PG restorers if structure is close enough and I think it is.

**Comment by owine** [comment]
Parse `log_path` in the backed up `ansible.cfg` to establish which flavor is being run.

**Comment by ben-ba** [comment]
A Migration path would be nice, to easy switching to Saltbox.

**Comment by saltydk** [comment]
> Parse `log_path` in the backed up `ansible.cfg` to establish which flavor is being run.

I don't see the point as there is no difference if you're restoring from Cloudbox or Saltbox currently. Ultimately all this boils down to changing a path if you want to have new backups go to a different folder than the Cloudbox one.

**Comment by saltydk** [comment]
Only the restore service brings over the config files so I am not really following what it is you ultimately want here. Please be specific and try not to ask for vague things.

**Comment by saltydk** [comment]
Closing this as I believe this is solved by our docs at this point.
