### ISSUE TITLE
Additional control over Saltbox apprise alerts

### ISSUE THREAD

**Issue by DomGrieco** [saltyorg/Saltbox#52]
Having a "logging-level" setting for the built in Saltbox apprise alerts. This could include "debug, info, warn, error" for example. It's self explanatory but for example "error" logging would only send alerts when task fail, such as back ups, rather than reporting all the successful runs like it does with todays behavior.

**Comment by saltydk** [comment]
If you take a regular bundle of notifications from one backup and then label them like you suggest what would they look like?

**Comment by DomGrieco** [comment]
Is this what you're looking for?

INFO/DEBUG : "Saltbox Backup: Started (snapshot-enabled) backup task."
DEBUG : "Saltbox Backup: Stopped Docker containers."
DEBUG : "Saltbox Backup: Started Docker containers."
DEBUG : "Saltbox Backup: Backup created with total size of"
DEBUG : "Saltbox Backup: Rclone uploaded backup to"
DEBUG : "Saltbox Backup: Rsync uploaded backup to"
INFO/DEBUG : "Saltbox Backup: Finished Saltbox (snapshot-enabled) backup task in"
INFO/DEBUG/ERROR: "Saltbox Backup: Backup terminated due to an error."

Some examples of new notifications could be error codes for each of the above info and/or debug notifications when they fail instead of the general catch all error message. Ideally, this option allows people the option to only have notifications be sent when something is wrong. Also, people who opt into the "INFO" setting would get far less notifications but still at the same frequency as their backup schedule.

As interesting idea as well is to have a "heartbeat" notification configured to send a notification every 7 days that just conveys that the notification system is still working.

Here is a suggestion of new apprise accounts configuration:
![image](https://user-images.githubusercontent.com/6556434/149704654-379dc4a3-406f-4905-99c8-bf9a72d13717.png)

**Comment by saltydk** [comment]
nothing prevents you from setting a heartbeat type thing in cron. I don't see the relevance to adding something like that in Saltbox itself though as it doesn't always run.

I get the general idea of the info/debug format but I guess I just don't see the point personally as one of the benefits is to track the size of the backup to catch size issues as well.

I am not opposed to implementing stuff at some point but not sure how to go about it exactly right now.
