### ISSUE TITLE
New rutorrent image - take 2.

### ISSUE THREAD

**Issue by saltydk** [saltyorg/Saltbox#57]
Try switching to https://github.com/romancin/rutorrent-docker since it includes pyrocore.

**Comment by JigSawFr** [comment]
@saltydk Why not use https://github.com/jesec/rtorrent with https://github.com/jesec/flood 👌

**Comment by saltydk** [comment]
Already have rtorrent with flood in sandbox.

**Comment by saltydk** [comment]
Again. Flood is already in sandbox. So it makes no sense so continue this
line of discussion. For most that use rutorrent flood isn't ready as a
replacement. On its own anyway.

**Comment by saltydk** [comment]
Once traefik3 is merged we'll be using our own image.
