### ISSUE TITLE
Sonarr var in Readarr Role

### ISSUE THREAD

**Issue by addbee** [saltyorg/Saltbox#59]
**Describe the bug**
Error when deploying readarr without sonarr.
sonarr_paths_location var used as destination when deploying readarr.

**To Reproduce**
sb install core
sb install readarr

**Expected behavior**
readarr install
[in this file](https://github.com/saltyorg/Saltbox/blob/master/roles/readarr/tasks/main2.yml)

**Comment by saltydk** [comment]
Should be fixed now.
