### ISSUE TITLE
Cant install Saltbox on fresh server

### ISSUE THREAD

**Issue by proelior** [saltyorg/Saltbox#65]
**Describe the bug**
Authorization Error
When following the link in the Google SDK step of the Saltbox install process the following error occurs.

Error 400: invalid_request
Missing required parameter: redirect_uri

**To Reproduce**
1. Follow the install up to the Google SDK step.
2. Run the commands for SDK install one at a time then run gcloud init.
3. Follow the generated link.
5. See error

**Expected behavior**
Login to your account and grant access to SDK.

**System Information**
 - Operating System: Ubuntu Server 20.04 LTS
 - Linux Kernel: 5.13.0-39-generic

**Comment by saltydk** [comment]
Please use the discord for support questions. This falls within a script not contained within this repo :)
