### ISSUE TITLE
Unnecessary ZeroSSL task when setting up Traefik

### ISSUE THREAD

**Issue by vpatel9202** [saltyorg/Saltbox#70]
**Describe the bug**
When installing (or reinstalling) Traefik, the current ansible role attempts to get EAB credentials from ZeroSSL without checking whether or not ZeroSSL has been enabled by the user in adv_settings.yml.

See [lines 55-57](https://github.com/saltyorg/Saltbox/blob/bf752c046df577e653150d2663f333d7417d8f2c/roles/traefik/tasks/main.yml#L55).

For whatever reason, ZeroSSL is throwing an error in my case so it would not allow me to complete the installation of my Traffik container and I was a bit confused on why I needed to get credentials from ZSSL to begin with since I have it disabled. I commented out the lines above and everything is running smoothly.

I do think the ZeroSSL error on my end is temporary and on their end rather than something related to Saltbox so that is not an issue here. The concern is strictly that this is an unnecessary point of failure for someone who isn't planning on using ZeroSSL anyway.

**Comment by saltydk** [comment]
This is intentional to allow setting zerossl on a per router basis and to make switching back and forth far less annoying. The only improvement we could explore is to check if we actually need to fetch new credentials (no key in the acme.json for example).
