### ISSUE TITLE
Preventing updates from resetting Cloudflare proxy status

### ISSUE THREAD

**Issue by vpatel9202** [saltyorg/Saltbox#72]
It seems that anytime we update a container, Saltbox resets Cloudflare DNS settings and turns off proxy for the respective subdomain. I know this is required for initial set up, but as far as I know, we did not have to turn off proxying during updates with Cloudbox. Is there some fundamental difference in the way Saltbox handles this that would require having proxy turned off for each update? Currently, I have to go into Cloudflare settings and manually turn on the proxy service for each subdomain after an update.

**Comment by saltydk** [comment]
https://docs.saltbox.dev/reference/accounts/#options-in-adv_settingsyml Read this and you'll find your answer.

**Comment by vpatel9202** [comment]
Sorry, I didn't see that in the docs when I set it up initially. Appreciate it, thanks!
