### ISSUE TITLE
Install scripts should not install on top of cloudbox

### ISSUE THREAD

**Issue by chazlarson** [saltyorg/Saltbox#79]
---

At least one person has attempted an in-place upgrade of a system with cloudbox actively installed.  This seems to be causing issues.

The scripts should look for some tell-tale sign of cloudbox and decline to proceed.

**Comment by saltydk** [comment]
Implemented in https://github.com/saltyorg/sb/commit/161ecab770528e4f081344ec7bae95e58f0b36b3
