### ISSUE TITLE
geoip plugin in ruTorrent does not function correctly

### ISSUE THREAD

**Issue by ben-burns** [saltyorg/Saltbox#87]
**Describe the bug**
In ruTorrent, the geoip plugin, when enabled, does not appear to function correctly.  It does not appear to resolve country data or display country flags for peers.

**To Reproduce**
1. Make sure the geoip plugin is enabled (restart the container if you just enabled it)
2. Click on an active torrect
3. Click the "Peers" tab
4. See the IP address / hostname of the connected peer with no country flag

**Expected behavior**
I would expect to see the country flag or details and not just the IP address or hostname of the peer.

**Screenshots**
Screenshot of geoip plugin not working:
![geoip plugin not working](https://i.imgur.com/7UVmDMX.png)

Screenshot of what geoip plguin should look like if it was working:
![geoip plugin working example](https://i.imgur.com/D6uvLXU.png)

**Logs**
There are no relevant logs available.  The plugin is status reports that it is loaded.

**System Information**

 - Operating System: Ubuntu Server 22.04 LTS
 - Linux Kernel: 5.15

**Additional context**
It may be worth exploring moving to something like https://github.com/Micdu70/geoip2-rutorrent instead

**Comment by saltydk** [comment]
We will be moving to the crazymax image once we nail down the migration bits.

**Comment by ben-burns** [comment]
> We will be moving to the crazymax image once we nail down the migration bits.

Great to hear, looking forward to it! Thank you

**Comment by saltydk** [comment]
Closing as this should be fixed when traefik3 is merged.
