### ISSUE TITLE
Change Traktarr to a container implementation

### ISSUE THREAD

**Issue by vpatel9202** [saltyorg/Saltbox#90]
---

Problem: Traktarr is currently installed direct to host OS which makes it more difficult to implement multiple instances. It would also make more sense in conjunction with the rest of this project to run this in a container.

Solution: I'm not adept with Ansible, but running Traktarr as a container is fairly straight forward as noted [here](https://github.com/Cloudbox/Cloudbox/issues/333#issue-527638518). I'm just not sure how to translate this over to Ansible.

**Additional context**
It is a PITA to implement multiple instances of Traktarr when installed as a daemon on the host system. The reason someone may need to run multiple instances is if they have multiple Plex libraries with identical content in different qualities. For example, let's say someone has a "Movies" section as well as "4K Movies" section. One instance of Traktarr can only monitor one of the two, so you would need to have a second instance to monitor the other. Implementing monitoring for multiple libraries of the same media type may be harder for Traktarr itself as it would entail changes to the core code, whereas implementing a containerized version in Saltbox would be much simpler.

**Comment by saltydk** [comment]
fairly simple to implement instances without containers but container wouldn't be a bad idea.

**Comment by saltydk** [comment]
I'll look at it tomorrow if I remember, if not feel free to ping me here or on discord.

**Comment by owine** [comment]
Even though we venv Traktarr now, this makes sense and would be helpful with that.

Only issue I see is that the CI on the image (which I didn't realize existed) appears to be broken.

**Comment by saltydk** [comment]
would probably just do traktarr2 bash wrapper to the new venv if going the host route. Depends how much people need the cli I suppose as that is slightly more annoying with docker I suppose

**Comment by saltydk** [comment]
kind of tempted to make every install venv for these things now that we have a format to do it instead of only on 22.04
