### ISSUE TITLE
Clarification on how plex_auth_token is implemented in autoscan vs cloudplow roles

### ISSUE THREAD

**Issue by vpatel9202** [saltyorg/Saltbox#92]
Looking at the autoscan role and cloudplow role, it seems that there is a difference in how the Plex Token is obtained and I'm wondering if this is intentional. The autoscan role obtains the token from Preferences.xml in the Plex directory while the cloudplow role depends on the plex_auth_token role, which then uses the API to resolve the token. Is there a reason for this difference or am I misunderstanding how the roles work?

**Comment by saltydk** [comment]
Autoscan scan role had to have multiple instance support so did a workaround for that at the time.

**Comment by saltydk** [comment]
Closing this but feel free to re-open if you respond.
